openapi: 3.0.2
info:
  title: Chess API
  version: 1.0.0
paths:
  /api/new_game:
    post:
      summary: Start a new chess game. Creates a board in the default state for a new game.
      operationId: newGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assistant_color:
                  description: The color of the assistant - "white" or "black"
                  type: string
              required:
                - assistant_color
      responses:
        "200":
          description: New game state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BoardState"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/move:
    post:
      summary: Make a chess move use SAN format. Convert from UCI if necessary. Display the results to the user.
      operationId: makeMove
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                move:
                  description: The move to make in SAN format
                  type: string
              required:
                - move
      responses:
        "200":
          description: Updated game state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BoardState"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BoardStateError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    BoardState:
      type: object
      properties:
        move_history:
          description: List of the moves that have been made so far in the game - e.g. "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Nxe4 5. Re1 Nd6 6. Nxe5 Be7 7. Bxc6"
          type: string
        FEN:
          description: The FEN (Forsyth-Edwards Notation) representation of the board - use this to determine where the pieces are
          type: string
        game_over:
          description: Whether the game is over or not
          type: boolean
        display:
          description: Markdown representation of the board to show to the user after each move
          type: string
        EXTRA_INFORMATION_TO_ASSISTANT:
          description: Extra information for the assistant
          type: string
      required:
        - move_history
        - FEN
        - game_over
        - display
        - EXTRA_INFORMATION_TO_ASSISTANT
    BoardStateError:
      type: object
      properties:
        error_message:
          description: Error message
          type: string
        move_history:
          description: List of the moves that have been made so far in the game - e.g. "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Nxe4 5. Re1 Nd6 6. Nxe5 Be7 7. Bxc6"
          type: string
        FEN:
          description: The FEN (Forsyth-Edwards Notation) representation of the board - use this to determine where the pieces are
          type: string
        game_over:
          description: Whether the game is over or not
          type: boolean
        display:
          description: Markdown representation of the board to show to the user after each move
          type: string
        EXTRA_INFORMATION_TO_ASSISTANT:
          description: Extra information for the assistant
          type: string
      required:
        - error_message
        - move_history
        - FEN
        - game_over
        - display
        - EXTRA_INFORMATION_TO_ASSISTANT
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
